# Generated by Django 4.0.4 on 2022-06-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule2', '0003_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.CharField(max_length=255),
        ),
    ]
